#!/usr/bin/env python3
"""Generate engine/scout/defaults/render-history.json from the release tags.

A vault's first upgrade to an engine that records `.scout-state/last-rendered/`
has no base to tell its own edits from template changes. This file holds a
signature of every managed file each older release shipped, so that upgrade can
recognise a file the vault never edited and update it silently (see
scout.scripts.vault_drift.Signature).

The file is frozen: releases from the one that introduced last-rendered/ record
their own bases, so only vaults last rendered by a release up to --through ever
read it. Re-run only to fix it, never as part of a release.

    engine/.venv/bin/python scripts/gen-render-history.py            # writes the file
    engine/.venv/bin/python scripts/gen-render-history.py --check    # exit 1 if it differs
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "engine"))

from scout.scripts.bootstrap import _MANAGED_FILES  # noqa: E402
from scout.scripts.vault_drift import RENDER_HISTORY, signature  # noqa: E402

# The last release that recorded no last-rendered/ base.
LAST_RELEASE_WITHOUT_BASES = "v0.11.0"


def _version(tag: str) -> tuple[int, ...]:
    return tuple(int(part) for part in tag.removeprefix("v").split("."))


def _git(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", "-C", str(ROOT), *args], capture_output=True, text=True, encoding="utf-8")


def build(through: str) -> dict:
    tags = sorted(
        (t for t in _git("tag", "--list", "v*").stdout.split() if _version(t) <= _version(through)),
        key=_version,
    )
    if not tags:
        raise SystemExit("no release tags found — run in a full clone (git fetch --tags)")
    if _git("cat-file", "-e", f"{tags[-1]}:engine/scout/__init__.py").returncode != 0:
        # In Raven-Scout/Scout (the former scout-plugin repo) the bare v* tags are the
        # plugin's pre-monorepo releases. A clone of the old app repo
        # (Raven-Scout/scout-app-legacy) carries the app's bare v* tags instead.
        raise SystemExit(
            f"tag {tags[-1]} is not a plugin release in this repository — run this from a full "
            "Raven-Scout/Scout clone, whose bare v* tags are the plugin's pre-monorepo releases"
        )
    files: dict[str, list[dict]] = {}
    for m in _MANAGED_FILES:
        by_hash: dict[str, dict] = {}
        for tag in tags:
            shown = _git("show", f"{tag}:{m.plugin_rel}")
            if shown.returncode != 0:
                continue  # not shipped by this release
            entry = signature(shown.stdout, rendered=m.rendered).to_json()
            by_hash.setdefault(entry["sha256"], {"versions": [], **entry})["versions"].append(tag)
        if by_hash:
            files[m.vault_rel] = list(by_hash.values())
    return {
        "schema_version": 1,
        "about": (
            "Signatures of every managed file the releases below shipped, so a vault's first upgrade "
            "can recognise one it never edited. Frozen: later releases record their own bases in "
            ".scout-state/last-rendered/. Generated by scripts/gen-render-history.py."
        ),
        "releases": tags,
        "files": files,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--through", default=LAST_RELEASE_WITHOUT_BASES)
    parser.add_argument("--check", action="store_true", help="compare with the committed file instead of writing")
    args = parser.parse_args()
    text = json.dumps(build(args.through), indent=1, ensure_ascii=False) + "\n"
    if args.check:
        current = RENDER_HISTORY.read_text(encoding="utf-8") if RENDER_HISTORY.exists() else ""
        if current != text:
            print(f"{RENDER_HISTORY} is out of date — re-run scripts/gen-render-history.py", file=sys.stderr)
            return 1
        return 0
    RENDER_HISTORY.write_text(text, encoding="utf-8")
    print(f"wrote {RENDER_HISTORY.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
