import Foundation
import Testing
@testable import Scout

/// The connector roster comes from `connectors.snapshot.json` (generated by
/// `scoutctl connectors snapshot`). When it can't be read the service must
/// fall back to the hardcoded list *and* say why, so the operator knows to
/// regenerate rather than silently losing rows from the health matrix.
@Suite("ConnectorHealthService roster")
struct ConnectorRosterTests {

    private func makeDir() throws -> URL {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("roster-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    private func writeSnapshot(_ json: String, in dir: URL) throws -> URL {
        let url = dir.appendingPathComponent("connectors.snapshot.json")
        try json.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    // MARK: - happy path

    @Test("a valid v1 snapshot yields its connector keys in order")
    func loadRoster_validSnapshot() throws {
        let dir = try makeDir(); defer { try? FileManager.default.removeItem(at: dir) }
        let url = try writeSnapshot("""
        {
          "schema_version": 1,
          "generated_from": "connectors.yaml",
          "connectors": [
            {"key": "mcp:claude_ai_Slack", "display_name": "Slack", "tier": "core"},
            {"key": "github", "display_name": "GitHub", "tier": "core"}
          ]
        }
        """, in: dir)

        let result = ConnectorHealthService.loadRoster(from: url)
        guard case let .success(keys) = result else {
            Issue.record("expected success, got \(result)")
            return
        }
        #expect(keys == ["mcp:claude_ai_Slack", "github"])
    }

    // MARK: - failure modes

    @Test("a missing snapshot names the path it looked at")
    func loadRoster_missingFile() throws {
        let dir = try makeDir(); defer { try? FileManager.default.removeItem(at: dir) }
        let absent = dir.appendingPathComponent("nope.json")

        guard case let .failure(err) = ConnectorHealthService.loadRoster(from: absent) else {
            Issue.record("expected failure for a missing snapshot")
            return
        }
        #expect(err.message.contains("snapshot not found"))
        #expect(err.message.contains(absent.path))
    }

    @Test("an unsupported schema version is rejected by number")
    func loadRoster_wrongSchemaVersion() throws {
        let dir = try makeDir(); defer { try? FileManager.default.removeItem(at: dir) }
        let url = try writeSnapshot("""
        {"schema_version": 2, "generated_from": "x", "connectors":
          [{"key": "a", "display_name": "A", "tier": "core"}]}
        """, in: dir)

        guard case let .failure(err) = ConnectorHealthService.loadRoster(from: url) else {
            Issue.record("expected failure for schema_version 2")
            return
        }
        #expect(err.message.contains("schema_version=2"))
    }

    @Test("an empty connector list is rejected rather than blanking the matrix")
    func loadRoster_emptyConnectorList() throws {
        let dir = try makeDir(); defer { try? FileManager.default.removeItem(at: dir) }
        let url = try writeSnapshot("""
        {"schema_version": 1, "generated_from": "x", "connectors": []}
        """, in: dir)

        guard case let .failure(err) = ConnectorHealthService.loadRoster(from: url) else {
            Issue.record("expected failure for an empty roster")
            return
        }
        #expect(err.message.contains("zero connectors"))
    }

    @Test("malformed JSON fails rather than throwing out of the loader")
    func loadRoster_malformedJSON() throws {
        let dir = try makeDir(); defer { try? FileManager.default.removeItem(at: dir) }
        let url = try writeSnapshot("{ not json at all", in: dir)

        guard case let .failure(err) = ConnectorHealthService.loadRoster(from: url) else {
            Issue.record("expected failure for malformed JSON")
            return
        }
        #expect(!err.message.isEmpty)
    }

    @Test("a snapshot missing required fields fails")
    func loadRoster_missingRequiredFields() throws {
        let dir = try makeDir(); defer { try? FileManager.default.removeItem(at: dir) }
        // No `generated_from`, and entries lack `tier`.
        let url = try writeSnapshot("""
        {"schema_version": 1, "connectors": [{"key": "a"}]}
        """, in: dir)

        guard case .failure = ConnectorHealthService.loadRoster(from: url) else {
            Issue.record("expected failure for an incomplete snapshot")
            return
        }
    }

    // MARK: - defaults

    @Test("the fallback roster is non-empty and free of duplicates")
    func fallbackConnectors_isSaneList() {
        let fallback = ConnectorHealthService.fallbackConnectors
        #expect(!fallback.isEmpty)
        #expect(Set(fallback).count == fallback.count)
        #expect(fallback.allSatisfy { !$0.isEmpty })
        #expect(fallback.contains("mcp:claude_ai_Slack"))
        #expect(fallback.contains("github"))
    }

    @Test("defaultConnectors always resolves a usable roster")
    func defaultConnectors_alwaysResolves() {
        // Either the bundled snapshot loads, or we get the hardcoded fallback —
        // never an empty roster, which would blank the health matrix.
        let connectors = ConnectorHealthService.defaultConnectors
        #expect(!connectors.isEmpty)
        #expect(Set(connectors).count == connectors.count)
    }

    @Test("the default snapshot URL points at a connectors.snapshot.json")
    func defaultSnapshotURL_namesTheSnapshotFile() {
        let url = ConnectorHealthService.defaultSnapshotURL
        #expect(url.lastPathComponent == "connectors.snapshot.json")
    }

    @Test("every roster key is already canonical")
    func fallbackConnectors_areCanonicalKeys() {
        for key in ConnectorHealthService.fallbackConnectors {
            #expect(ConnectorKeyAlias.canonical(key) == key,
                    "\(key) is not its own canonical form")
        }
    }
}
